name: Go
on:
  pull_request:
  push:
    branches: [master]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.49.0

      - name: Test
        run: go test -v ./...
